services:
  pixel-postgres:
    image: postgres:16
    container_name: pixel_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: pixel_db
    ports:
      - "5432:5432"
    volumes:
      - pixel_postgres_data:/var/lib/postgresql/data

volumes:
  pixel_postgres_data: